import { getStore } from "@netlify/blobs";
export const STORE_NAME="yachiyo-public-site", BACKUP_ROOT="backups/monthly/", MANUAL_ROOT="backups/manual/", MANIFEST_NAME="__manifest.json", MAX_MONTHLY_BACKUPS=12;
const EXCLUDED_PREFIXES=["backups/","auth/","rate-limit/","ratelimit/","locks/","lock/"];
const EXCLUDED_KEYS=new Set(["content/access-settings.json","content/coach-attendance-access.json","content/live-score-lock.json","content/live-score-viewers.json"]);
export function isBackupableKey(key){const v=String(key||"");return !!v&&!EXCLUDED_KEYS.has(v)&&!EXCLUDED_PREFIXES.some(p=>v.startsWith(p));}
const safe=v=>String(v||"").replace(/[^0-9A-Za-z._-]/g,"-").slice(0,80);
const prefix=(kind,id)=>`${kind==="manual"?MANUAL_ROOT:BACKUP_ROOT}${safe(id)}/`;
export async function listBackupableBlobs(store=getStore({name:STORE_NAME,consistency:"strong"})){const {blobs=[]}=await store.list();return blobs.filter(x=>isBackupableKey(x.key));}
async function copy(store,from,to){const value=await store.get(from,{type:"arrayBuffer",consistency:"strong"});if(value==null)return false;await store.set(to,value);return true;}
export async function createBackup({kind="monthly",reason="automatic"}={}){const store=getStore({name:STORE_NAME,consistency:"strong"}),now=new Date(),id=kind==="manual"?now.toISOString().replace(/[:.]/g,"-"):now.toISOString().slice(0,7),p=prefix(kind,id),mk=`${p}${MANIFEST_NAME}`;const old=await store.get(mk,{type:"json",consistency:"strong"});if(old?.complete&&kind==="monthly")return old;const blobs=await listBackupableBlobs(store),keys=[];for(const item of blobs){if(await copy(store,item.key,`${p}data/${item.key}`))keys.push(item.key);}const manifest={version:1,id,kind,reason,createdAt:now.toISOString(),complete:true,itemCount:keys.length,keys};await store.setJSON(mk,manifest);if(kind==="monthly")await pruneMonthlyBackups(store);return manifest;}
export async function listBackups(){const store=getStore({name:STORE_NAME,consistency:"strong"}),{blobs=[]}=await store.list({prefix:"backups/"}),out=[];for(const item of blobs.filter(x=>x.key.endsWith(`/${MANIFEST_NAME}`))){const m=await store.get(item.key,{type:"json",consistency:"strong"});if(m?.complete)out.push(m);}return out.sort((a,b)=>String(b.createdAt).localeCompare(String(a.createdAt)));}
export async function pruneMonthlyBackups(store=getStore({name:STORE_NAME,consistency:"strong"})){const {blobs=[]}=await store.list({prefix:BACKUP_ROOT}),ids=[...new Set(blobs.map(x=>x.key.slice(BACKUP_ROOT.length).split("/")[0]).filter(Boolean))].sort().reverse();for(const id of ids.slice(MAX_MONTHLY_BACKUPS)){const p=prefix("monthly",id),{blobs:old=[]}=await store.list({prefix:p});for(const item of old)await store.delete(item.key);}}
export async function restoreBackup(kind,id){const store=getStore({name:STORE_NAME,consistency:"strong"}),p=prefix(kind,id),manifest=await store.get(`${p}${MANIFEST_NAME}`,{type:"json",consistency:"strong"});if(!manifest?.complete||!Array.isArray(manifest.keys))throw new Error("backup not found");const safety=await createBackup({kind:"manual",reason:`before-restore:${kind}:${id}`}),current=await listBackupableBlobs(store);for(const item of current)await store.delete(item.key);let restored=0;for(const key of manifest.keys){if(isBackupableKey(key)&&await copy(store,`${p}data/${key}`,key))restored++;}return {restored,manifest,safetyBackup:safety};}
