[build]
  publish = "."
  functions = "netlify/functions"

[functions]
  node_bundler = "esbuild"

[[redirects]]
  from = "/rules"
  to = "/board.html"
  status = 301
  force = true

[[redirects]]
  from = "/rules.html"
  to = "/board.html"
  status = 301
  force = true
